spring.application.name=productivity_timecard
logging.level.org.springframework.data.mongodb.core=DEBUG
logging.level.org.mongodb.driver.cluster=DEBUG
db.user=mukherjeetejas
db.password=SlSdI9KZe3juspHe
db.cluster=cluster0.6peswns.mongodb.net
db.database=productivity